### ISSUE TITLE
Feature Request: Turning Figure Visibility Off

### ISSUE THREAD

**Issue by kakurk** [memobc/memolab-fmri-qa#5]
Hey @ritcheym,

@rsamide mentioned that she wanted to run the memloab-fmri-qa pipeline multiple times with different parameters and ideally wanted to be able to run it using BC's job queueing system.

The problem she ran into was that there is not easy way to turn the figure visibility off to facilliate submission to a job queuing system.

Do you think is might be useful to add such a feature? I figure that I could make various changes to the graphing code in the relevant modules (i.e., `compute_snr.m` and `theplot.m`) and set it up in such a way that the user could control figure visibility by simply changing a new input parameter (something like `FigureVisibility = true; % set to false to make ALL figures invisible` in the base `memolab_qa_pipeline.m` script)

**Comment by ritcheym** [comment]
I vote for forcing the figures. Putting eyes on the data is an important part of QA.
